env:
  global:
    - MODULE_NAME=Regex
matrix:
  include:
    - script:
        - open -b com.apple.iphonesimulator #https://github.com/travis-ci/travis-ci/issues/3040#issuecomment-146700203
        - swift build
        - swift test
        - xcodebuild test -project $MODULE_NAME.xcodeproj -scheme $MODULE_NAME-OSX
        - xcodebuild test -project $MODULE_NAME.xcodeproj -scheme $MODULE_NAME-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7 Plus'
        - sleep 20
        - xcodebuild test -project $MODULE_NAME.xcodeproj -scheme $MODULE_NAME-tvOS -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV 1080p'
        - xcodebuild build -project $MODULE_NAME.xcodeproj -scheme $MODULE_NAME-watchOS -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch - 42mm'
      os: osx
      osx_image: xcode9.4 #xcode9
      language: objective-c
      env:
        - secure: "fZvksctuVyyVZ4Oz6iTaFhQl+lnj4YJs3UPGu7e/S8humZxRDvOBNba1l5Ip8FekP10dKGLTL77VfmS/bjUJTJKBbFDI9RcXEnN5ZQCaGPErTyIeJ+I7Apl08pfSHyJBE22zrIboHRQi+kxedSthHaTVBHsbVMz6eNyYA8Q4qAvx0IoWkKZ5vULKzqwlXpA13sQ5l4nJ34Aq8wJrzAe/y0vGmwKyrP4RxsEpmYIfbjqnxVfYgRMP+GUgkKBwnYYamTEE8zCiXV6d6QDFWPSo3Ay8SWd5RvjqjsXI5POP77sPikizd+Tqd7fNiHM0ImimbuqiWTsxRWiEYFpep0Xy3WGNeyTpzh/RkZhPwUPNLBr+OE+ZsfDcQHyexsyIqE7GZN0fRaC7zTvNjv6ZBo4qp3aTXLZbMw0wPCQBkjh4k+9hJRbrlJd3v9VKZHCkXCxU43ikTWFrPnqYbUEbYNqyjDL6voCYWHWytHOiKsxcCa2X6ju8XB3uWZA0+jxBkCuJhqIFFpYM7H//Eqtd46YEO5nHDf00ivNMdg/KGPFFuJJnHdcqow+wcrHTrtWMoYk0q6RgJ+3LvqKhJ9CxxEWutNJnMBizF+jbKWX5g3PwHEiA595Zh5mnRLLdTMh/3u7R2/Lp0yKG763+bdXNPXxoLuR9bw7rUM9+AfNWloxmiCg="
      before_install:
        - brew update
        - brew outdated carthage || brew upgrade carthage
        # - brew outdated xctool || brew upgrade xctool
      before_script:
        # bootstrap the dependencies for the project
        # you can remove if you don't have dependencies
        # - carthage bootstrap
      before_deploy:
        - carthage build --no-skip-current
        - carthage archive $MODULE_NAME
        - pod trunk push CrossroadRegex.podspec --allow-warnings
      deploy:
        provider: releases
        api_key:
          secure: otlenNknpFmBzz2PvrDhTp5cJJyvQDMztPqUnj49aVnIuTx0BdMT2xYOX2UZS/2PnCWlEvCgpvoGr8cbB3H5cI459THBKaTGr16u17Tc9Nk14na+BQAV+aIxnC0ffYe1OT+qPMsvm5tUsxvqun/3XO7jM4LKDBOm9CkRVSDgflA+7w38gJ2F+j7gtyk4RdBkFMsp04CxpXEMND8AsPStKU3hoeRSS8mKvwWqMD8aXsKJwOXr7vpGT9LpPJ5qkS64TazY7oCjL+0wG22Yz2+gQ+97nhyRjHmhBtQoQx32ocjQ70JFU/fAqgisk+8uPDqJXvIpU3QLOrLhQTNhR4EGaVl3P4wbwjGexWKshrraEUhQj7ma2c7b05BfES7qEc1LymNrqvU2COu5uUVMyXJQQYTNVik4qe2oXbawv9k1i98BMgECMmmW3YXlX0S+sOjVfLML1PZ6Raj6LhYkTNJYUBjanSYGUDPCxvx1lC8pHEeTnL7g3AcAGNHxn6o+f3fHvsOR/aE/RwznD0oGz0pRis2uJeMoMJhykNx/YyrLVowfy4HI8gUKpU88AdE4vPhLm8SpZv5fFUmmgQkH9bKEJTKCXgSCcITyehlK8aIisMvPCejizuZj2kpCt/fKXudwODaiXFaPzNqzTxLK8oJLSZyvWpaVPXowGCEpFi5917w=
        file: $MODULE_NAME.framework.zip
        skip_cleanup: true
        on:
          repo: crossroadlabs/Regex
          tags: true
    - script:
        - swift build
        - swift test
      sudo: required
      dist: trusty
      language: generic
      before_install:
        # install original swift distribution
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - cd ..
        - export BRANCH="swift-4.0.2-release"
        - export LINUX_VERSION="ubuntu14.04"
        - export SWIFT_VERSION="swift-4.0.2-RELEASE"
        - LINUX_VERSION_GLUED=`echo $LINUX_VERSION | perl -n -e'/^(.*?)\.(.*)$/; print "$1$2"'`
        - export RELEASE_NAME="$SWIFT_VERSION-$LINUX_VERSION"
        - wget "https://swift.org/builds/$BRANCH/$LINUX_VERSION_GLUED/$SWIFT_VERSION/$RELEASE_NAME.tar.gz"
        - tar xzf $RELEASE_NAME.tar.gz
        - export PATH="${PWD}/$RELEASE_NAME/usr/bin:${PATH}"
        - export LD_LIBRARY_PATH="${PWD}/$RELEASE_NAME/usr/lib/swift/linux/:$LD_LIBRARY_PATH"
        # get back home
        - cd $MODULE_NAME
notifications:
  email: false
